good       = "test/Maps/good_map.map"
not_real   = "test/Maps/doesnt_exist.map"
sample     = "test/Maps/sample_string.map"
no_player  = "test/Maps/no_player.map"
empty      = "test/Maps/empty_map.map"
bad_col    = "test/Maps/bad_map.map"
impossible = "test/Maps/impossible.map"